<?php
return [
    'addNew'=>'যুক্ত করুন',
    'code'=>'কোড',
    'listTitle'=>'বিভাগ তালিকা',
    'createTitle'=>'বিভাগ তৈরি করুন',
    'editTitle'=>'বিভাগ সম্পাদন করুন',
    'vsmPlaceholderSearch'=>'ভিএসএম খুজুন ',
    'vsmPlaceholderStatusSearch'=>'বর্তমান অবস্থা',
    'searchPlaceholder'=>'খুঁজুন',
    'serial'=>'ক্রমিক নং',
    'name'=>'নাম(ইংরেজি)',
    'nameBengali'=>'নাম(বাংলা)',
    'status'=>'অবস্থান',
    'action'=>'কর্ম পরিকল্পনা',
    'statusSearch'=>[
        'active'=>'সক্রিয়',
        'inactive'=>'নিষ্ক্রিয়',
        'deleted'=>'মুছে ফেলা',
    ],
    'edit'=>'সম্পাদনা করুন',
    'delete'=>'মুছে ফেলুন',
    'storeMessage'=>'বিভাগ সফলভাবে সংরক্ষণ করা হয়েছে',
    'editMessage'=>'বিভাগ সফলভাবে সম্পাদিত হয়েছে',
    'deleteMessage'=>'বিভাগ সফলভাবে সফলভাবে মুছে ফেলা হয়েছে',
    'deleteConfirmMessage'=>'আপনি সত্যিই কি এই বিভাগ মুছে ফেলতে চান?',
    'statusActiveSearch'=>'সক্রিয়',
    'statusInactiveSearch'=>'নিষ্ক্রিয়',
    'statusDeleteSearch'=>'মুছে ফেলা',
    'notDeletedMessage'=>'বিভাগ টি চুক্তিবদ্ধ রয়েছে তাই মুছে ফেলা যাচ্ছেনা',
];